---
title: "Introduction to grover"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to grover}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

The `grover` package provides a web-based API framework for remote access to a mass spectrometry `.raw` data repository, implemented using the [`plumber`](https://www.rplumber.io/) R package
API functionality includes:

* **File information** retrieval including file size and creation dates.
* File **transfer**.
* Raw mass spectrometry data file **conversion** to `.mzML` format.
* Retrieval of **sample information** from `.raw` file headers.

The package functionality is platform independent with file conversion and sample information retrieval functionality available through use of the [`msconvereR`](https://github.com/wilsontom/msconverteR) and [`rawrr`](https://github.com/fgcz/rawrr) R packages.

## Installation

The `grover` package can be installed from GitHub using the following:

```
remotes::install_github('jasenfinch/grover',build_vignettes = TRUE)
```

## Package usage

Use of the `grover` package can be divided into the following topics:

* **Hosting raw mass spectrometry data repository using a grover API.** Details of how to do this can be found in the [Hosting a grover API](hosting.html) vignette.

* **Accessing data from a mass spectrometry data repository hosted by a grover API.** See the [Accessing raw mass spectrometry data from a grover API](client-usage.html) vignette for an overview of how this can be achieved.
